In [1]:
import numpy as np
import pandas as pd
import nltk
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from pathlib import Path
from dotenv import load_dotenv
import os

from nltk.tokenize import word_tokenize
from gensim.models import Word2Vec
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
# Auxiliares
def truncar_texto(texto, limite=100):

    texto = str(texto)

    if len(texto) <= limite:
        return texto

    return texto[:limite] + "..."


def vetor_medio_documento(tokens, model, vector_dim):

    vetores = [
        model.wv[token]
        for token in tokens
        if token in model.wv
    ]

    if len(vetores) == 0:
        return np.zeros(vector_dim)

    return np.mean(vetores, axis=0)

In [3]:
try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    nltk.download("punkt")
    nltk.download("punkt_tab")


# Função Principal
def analisar_similaridade_w2v(
    df,
    colunas=["stop", "stop_lemma", "stop_stem"],
    top_n=30,
    vector_dim=100,
    window_size=5,
    min_word_count=1,
    sg=0,
    random_state=42
):

    for coluna in colunas:

        print("\n" + "=" * 90)
        print(f"ANALISANDO COLUNA: {coluna}")
        print("=" * 90)

        # Preparação
        dados = (
            df[coluna]
            .fillna("")
            .astype(str)
            .reset_index(drop=True)
        )

        dados = dados[dados.str.strip() != ""].reset_index(drop=True)

        if len(dados) < 2:
            print(f"Coluna {coluna} possui poucos dados.")
            continue

        documentos = dados.tolist()

        query = documentos[0]

        print("\nQUERY:")
        print(query)

        # Tokenização
        documentos_tokenizados = [
            word_tokenize(doc.lower())
            for doc in documentos
        ]

        # Words2Vec
        model_w2v = Word2Vec(
            sentences=documentos_tokenizados,
            vector_size=vector_dim,
            window=window_size,
            min_count=min_word_count,
            workers=4,
            sg=sg,
            seed=random_state
        )

        print(
            f"\nVocabulário: "
            f"{len(model_w2v.wv.index_to_key)} palavras"
        )

        # Vetores docs
        vetores_documentos = np.array([
            vetor_medio_documento(
                tokens,
                model_w2v,
                vector_dim
            )
            for tokens in documentos_tokenizados
        ])

        query_tokens = word_tokenize(query.lower())

        vetor_query = vetor_medio_documento(
            query_tokens,
            model_w2v,
            vector_dim
        )

        # Similaridade query x documentos
        similaridades = cosine_similarity(
            vetor_query.reshape(1, -1),
            vetores_documentos
        )[0]

        resultado = pd.DataFrame({
            "indice": range(len(documentos)),
            "documento": documentos,
            "similaridade": similaridades
        })

        # remove a própria query
        resultado = resultado[resultado["indice"] != 0]

        # Top mais similares
        top_similares = (
            resultado
            .sort_values(
                "similaridade",
                ascending=False
            )
            .head(top_n)
            .reset_index(drop=True)
        )

        # Menos similares
        top_menos = (
            resultado
            .sort_values(
                "similaridade",
                ascending=True
            )
            .head(top_n)
            .reset_index(drop=True)
        )

        # # HEATMAPS QUERY x DOCUMENTOS
        # fig = make_subplots(
        #     rows=1,
        #     cols=2,
        #     subplot_titles=(
        #         f"{top_n} MAIS SIMILARES",
        #         f"{top_n} MENOS SIMILARES"
        #     ),
        #     horizontal_spacing=0.08
        # )

        # z_top = np.array([
        #     top_similares["similaridade"].values
        # ])

        # z_bottom = np.array([
        #     top_menos["similaridade"].values
        # ])

        # # Top
        # fig.add_trace(

        #     go.Heatmap(
        #         z=z_top,

        #         x=top_similares["indice"],

        #         y=["similaridade"],

        #         customdata=np.array(
        #             top_similares["documento"]
        #         ).reshape(1, -1),

        #         text=np.round(
        #             top_similares["similaridade"],
        #             4
        #         ),

        #         texttemplate="%{text}",

        #         hovertemplate=
        #             "<b>Índice:</b> %{x}<br>" +
        #             "<b>Similaridade:</b> %{z:.4f}<br><br>" +
        #             "<b>Documento:</b><br>" +
        #             "%{customdata}<extra></extra>",

        #         colorscale="Blues"
        #     ),

        #     row=1,
        #     col=1
        # )

        # # Bottom
        # fig.add_trace(

        #     go.Heatmap(
        #         z=z_bottom,

        #         x=top_menos["indice"],

        #         y=["similaridade"],

        #         customdata=np.array(
        #             top_menos["documento"]
        #         ).reshape(1, -1),

        #         text=np.round(
        #             top_menos["similaridade"],
        #             4
        #         ),

        #         texttemplate="%{text}",

        #         hovertemplate=
        #             "<b>Índice:</b> %{x}<br>" +
        #             "<b>Similaridade:</b> %{z:.4f}<br><br>" +
        #             "<b>Documento:</b><br>" +
        #             "%{customdata}<extra></extra>",

        #         colorscale="Reds"
        #     ),

        #     row=1,
        #     col=2
        # )

        # # gráfico
        # fig.update_layout(
        #     title=f"QUERY x DOCUMENTOS — {coluna}",
        #     height=500,
        #     width=1600
        # )

        # fig.show()

        # Doc x Doc
        indices_heatmap = (
            top_similares["indice"].tolist()
            +
            top_menos["indice"].tolist()
        )

        indices_heatmap = list(
            dict.fromkeys(indices_heatmap)
        )

        docs_heatmap = [
            documentos[i]
            for i in indices_heatmap
        ]

        vetores_heatmap = vetores_documentos[
            indices_heatmap
        ]

        # Matriz similaridade
        matriz_sim = cosine_similarity(
            vetores_heatmap
        )

        labels = [
            f"{i}"
            for i in indices_heatmap
        ]

        # Heatmap Docs
        fig2 = px.imshow(
            matriz_sim,

            x=labels,
            y=labels,

            color_continuous_scale="Viridis",

            text_auto=".2f",

            aspect="auto"
        )

        customdata = []

        for linha_texto in docs_heatmap:

            linha_custom = []

            for coluna_texto in docs_heatmap:

                linha_custom.append([

                    truncar_texto(linha_texto, 100),

                    truncar_texto(coluna_texto, 100)
                ])

            customdata.append(linha_custom)

        customdata = np.array(customdata)

        fig2.update_traces(

            customdata=customdata,

            hovertemplate=
                "<b>Texto Linha:</b><br>%{customdata[0]}<br><br>" +
                "<b>Texto Coluna:</b><br>%{customdata[1]}<br><br>" +
                "<b>Similaridade:</b> %{z:.4f}<br>" +
                "<extra></extra>"
        )

        fig2.update_layout(
            title=(
                f"SIMILARIDADE DOCUMENTO x DOCUMENTO "
                f"({coluna})"
            ),
            height=1000,
            width=1000
        )

        fig2.show()

        # Tabelas
        print("\nTOP MAIS SIMILARES")
        display(
            top_similares[
                ["indice", "similaridade", "documento"]
            ]
        )

        print("\nTOP MENOS SIMILARES")
        display(
            top_menos[
                ["indice", "similaridade", "documento"]
            ]
        )

In [4]:
env_path = Path("..") / ".env"
load_dotenv(dotenv_path=env_path)

nome_arquivo = os.getenv("NOMALIZED_FILE_NAME")

caminho_csv = Path("..") / "data_output" / nome_arquivo

df = pd.read_csv(caminho_csv)

analisar_similaridade_w2v(
    df=df
)

==========================================================================================
ANALISANDO COLUNA: stop
==========================================================================================

QUERY:
oitava natal senhor jesus cristo dia circuncisão solenidade santa maria mãe deus concílio éfeso padres aclamaram theotókos porque nela verbo fez carne habitou homens filho deus príncipe paz dado nome acima todos nomes

Vocabulário: 16298 palavras

TOP MAIS SIMILARES

    indice  similaridade                                          documento
0     3242      0.999833  roma beata maria beltrame quattrócchi mãe famí...
1     4091      0.999788  são paulo cruz presbítero desde juventude dist...
2      438      0.999708  bordéus frança santa joana lestonnac ainda ado...
3      301      0.999687  viena áustria beato ladislau batthyány-strattm...
4     4486      0.999628  santa margarida nascida hungria casada malcom ...
5       70      0.999605  solenidade epifania senhor celebra tríplice ma...
6     1462      0.999502  festa santa catarina sena virgem doutora igrej...
7     2307      0.999476  santa isabel rainha portugal admirável interve...
8     3917      0.999455  memória senhora rosário dia recitação rosário ...
9     1024      0.999421  valdstena suécia santa catarina virgem filha s...
10    4936      0.999388  passados inumeráveis séculos desde criação mun...
11     854      0.999359  santa francisca romana religiosa dada casament...
12    4954      0.999358  song-khon localidade tailândia beatas mártires...
13    2491      0.999314  senhora carmo evoca monte carmelo onde profeta...
14    4043      0.999302  santa edviges religiosa natural baviera duques...
15    3536      0.999246  festa exaltação santa cruz dia seguinte dedica...
16    4058      0.999233  materdómini campânia são gerardo majella relig...
17    3241      0.999220  fortaleza kharsk perto tomsk sibéria região rú...
18      54      0.999179  emmetsburg cidade maryland estados unidos amér...
19    3818      0.999173  memória santa teresa menino jesus virgem douto...
20    2742      0.999121  memória santos marta maria lázaro irmãos espír...
21    2691      0.999084  la valetta ilha malta são jorge preca presbíte...
22     909      0.999061  ernée território mayenne frança beata francisc...
23    4809      0.999034  12 ♦ goradze bósna-herzegovina beatas maría ju...
24    2411      0.998975  cesareia mauritânia argélia santa marciana vir...
25    3030      0.998974  solenidade assunção virgem santa maria mãe deu...
26    2801      0.998966  memória santo afonso maria ligório bispo douto...
27    1652      0.998965  senhora fátima portugal cuja contemplação luga...
28    2875      0.998955  festa transfiguração senhor jesus cristo filho...
29    2601      0.998869  santa brígida religiosa contraindo matrimónio ...

TOP MENOS SIMILARES

    indice  similaridade                                          documento
0     3898      0.837444  rímini marcas região itália beato alberto marv...
1     1632      0.837998  varennes território langres gália actualmente ...
2     2029      0.841698  auxerre gália lionense actualmente frança são ...
3     1550      0.842737  vienne gália lionense actual frança são nicéci...
4     3091      0.845720  metz gália bélgica actualmente frança são firm...
5      566      0.845965  château-landon gália actualmente frança são se...
6     3787      0.846142  auxerre gália lionense actual frança são frate...
7     2514      0.847096  auxerre gália lionense actualmente frança são ...
8     3271      0.847363  saintes gália actualmente frança são viviano b...
9      188      0.847572  gévaudan gália actualmente frança são firmino ...
10    4381      0.847576  verdun gália bélgica actualmente frança são vi...
11    2589      0.847896  menat gália arvenense actual frança são menele...
12    4068      0.848972  orange provença região gália actual frança são...
13    1752      0.849120  castagneto etrúria região itália beato guido g...
14    3933      0.849132  ruão gália lionense actualmente frança santo e...
15    1849      0.849492  orange provença região gália actualmente franç...
16    3230      0.850066  auxerre gália lionense actualmente frança sant...
17     585      0.851462  carcassone gália narbonense actual frança são ...
18    1084      0.851614  senlis gália lugdunense actual frança são régu...
19    3723      0.851620  chartres gália lionense hodierna frança são so...
20     204      0.852098  chartres nêustria actualmente frança são malar...
21    4567      0.852168  autun gália lionense hodierna frança são pragm...
22    3388      0.852332  chartres nêustria actualmente frança são calét...
23    3287      0.852568  metz gália bélgica actualmente frança santo ad...
24     847      0.853045  pavia lombardia região itália são litifredo bispo
25    2764      0.853310  auxerre gália lionense actual frança santo urs...
26    2271      0.853386  vienne gália lionense actual frança são martin...
27    2934      0.853391  palena calábria actualmente abruzos região itá...
28    1586      0.853493  auxerre gália lionense actual frança santo elá...
29     610      0.853682    cápua campânia região itália são decoroso bispo

==========================================================================================
ANALISANDO COLUNA: stop_lemma
==========================================================================================

QUERY:
oitar natal senhor jesus cristo dia circuncisão solenidade santo Maria mãe Deus concílio éfeso padre aclamar theotókos porque em ela verbor fazer carne habitou homem filho Deus príncipe paz dar nome acima todo nome

Vocabulário: 15134 palavras

TOP MAIS SIMILARES

    indice  similaridade                                          documento
0     2491      0.999674  senhora Carmo evocar Monte carmelo onde Profet...
1     3971      0.999630  são João xxiii papar homem dotar extraordinári...
2     2149      0.999606  beata sancha mafalda virgem terês religioso fi...
3     4043      0.999515  Santa edviges religioso natural baviera duques...
4     3818      0.999488  memória santo teresa menino jesus virgem douto...
5     1285      0.999435  schiedar géldr santo Ludovina virgem pôr confi...
6     4496      0.999432  memória santo isabel hungr ser jovem dar casam...
7      438      0.999416  bordéu França santo joana lestonnac ainda adol...
8     3174      0.999349  Santa Rosa virgem insigne desde tenra idade au...
9     1305      0.999306  romar são Bento José Labre aspirar desde adole...
10     265      0.999236  palestina santo eutímio abader ser natural arm...
11    1652      0.999232  senhora fátimo Portugal cujo contemplação luga...
12      70      0.999218  solenidade Epifania senhor celebrar tríplice m...
13    3543      0.999216  ében povoação tirol hodierno áustrio santo not...
14     301      0.999175  vieno áustrio beato ladislau batthyány-strattm...
15    3939      0.999153  são João Leonardo presbítero luca etrúrio regi...
16    4771      0.999092  Lima peru santo narciso jesus Martillo moran v...
17    4486      0.999060  Santa margarido nascido Hungria casado malcom ...
18    3917      0.999056  memória senhor rosário dia recitação rosário c...
19    2801      0.999027  memória santo Afonso Maria ligório Bispo douto...
20    1462      0.999014  festa santo catarina seno virgem doutorar igre...
21    4936      0.999011  passar inumerável século desde criação mundo p...
22    3574      0.998981  wilton Inglaterra santa Edite virgem filhar re...
23    2691      0.998976  la valetta ilha malto são Jorge Preca presbíte...
24    2601      0.998917  santo brígido religioso contrair matrimónio su...
25     242      0.998910  budapeste hungr Santa margarer virgem filhar r...
26    3870      0.998910  memória são francisco vida despreocupar conver...
27    3241      0.998900  fortalezar kharsk perto tomsk sibério Região R...
28    4091      0.998842  são Paulo Cruz presbíterar desde Juventude dis...
29    1603      0.998795  tebaido região egipto são pacómio abade ainda ...

TOP MENOS SIMILARES

    indice  similaridade                                          documento
0     1632      0.812135  varenne território langr gália actualmente Fra...
1     2029      0.817394  auxerrer gália lionense actualmente França são...
2     3898      0.818013  rímini marca Região itália beato Alberto marvelli
3     1353      0.820122  auxerrer gália lionense actual França são marc...
4     3091      0.820205  metz gália bélgico actualmente França são Firm...
5     3271      0.821312  sainte gália actualmente França são viviano Bispo
6     4381      0.821786  verdun gália bélgico actualmente França são vi...
7      566      0.822585  château-landon gália actualmente França são se...
8     1550      0.822618  vienne gália lionense actual França são nicéci...
9     2514      0.822639  auxerrer gália lionense actualmente França são...
10     188      0.822938  Gévaudan gália actualmente França são Firmino ...
11    4068      0.825749  orange provençar Região gália actual França sã...
12    3787      0.825899  auxerrer gália lionense actual França são frat...
13    2071      0.826439  Limoges aquitânia actualmente França são salmó...
14    1849      0.827073  orange provençar Região gália actualmente Fran...
15    2589      0.829034  menat gália arvenense actual França são menele...
16     585      0.829118  carcassone gália narbonense actual França são ...
17    3287      0.829929  metz gália bélgico actualmente França santo ad...
18    1084      0.830148  senli gália lugdunense actual França são régul...
19    3933      0.830283  ruão gália lionense actualmente França santo e...
20    3230      0.830589  auxerrer gália lionense actualmente França san...
21    3388      0.830798  chartr nêustrio actualmente França são calétri...
22    2934      0.830886  paleno calábrio actualmente abruzo Região itál...
23     204      0.831023  chartr nêustrio actualmente frança são Malardo...
24    2654      0.831246  metz gália bélgico actualmente França santa gl...
25     529      0.831879  besançon borgonhar actualmente França são nicé...
26    4889      0.832402  auxerrer gália lionense actualmente França são...
27    2271      0.834360  vienne gália lionense actual França são martin...
28    4567      0.834916  Autun gália lionense hodierno França são pragm...
29    1586      0.834983  auxerrer gália lionense actual França santo el...

==========================================================================================
ANALISANDO COLUNA: stop_stem
==========================================================================================

QUERY:
oit natal senh jesu crist dia circuncis solen sant mar mãe deu concíli éfes padr aclam theotók porqu nel verb fez carn habit hom filh deu príncip paz dad nom acim tod nom

Vocabulário: 12177 palavras

TOP MAIS SIMILARES

    indice  similaridade                                          documento
0     3917      0.999582  memór senh ros dia recit ros coro mari invoc a...
1      438      0.999542  bordéu franç sant joan lestonnac aind adolesc ...
2     3160      0.999398  memór virgem sant mar rainh deu luz filh deu p...
3       35      0.999398  sant nom jesu únic nom tud céu terr abism ajoe...
4     4091      0.999366  são paul cruz presbíter desd juventud distingu...
5     4936      0.999234  pass inumer sécul desd cri mund princípi deu c...
6     3548      0.999102  memór senh dor est pé junt cruz jesu associ ín...
7      854      0.999086  sant francisc roman religi dad cas aind adoles...
8      301      0.999059  vien áustr beat ladislau batthyány-strattmann ...
9     1462      0.999033  fest sant catarin sen virgem dou igrej tend to...
10    2875      0.998984  fest transfigur senh jesu crist filh unigénit ...
11    1285      0.998856  schied géldr sant ludovin virgem pond confianç...
12    4771      0.998833  lim peru sant narcis jesu martill moran virgem...
13      70      0.998825  solen epifan senh celebr trípl manifest grand ...
14    4486      0.998754  sant margar nasc hungr cas malcom iii rei escó...
15    4058      0.998748  materdómin campân são gerard majell religi con...
16    4018      0.998737  balas próx brag portug beat alexandrin mar cos...
17     431      0.998676  fest   apresent senh greg cham hypap quarent d...
18    3939      0.998672  são joã leonard presbíter luc etrúr reg itál d...
19    3648      0.998656  fest são mat apóstol evangel denomin lev cham ...
20    2691      0.998581  la valett ilh malt são jorg prec presbíter ded...
21    4762      0.998571  solen imacul conce virgem sant mar verdade che...
22    2438      0.998538  comemor sant esdr sacerdot escrib temp artaxer...
23    2491      0.998502  senh carm evoc mont carmel ond profet eli reco...
24     297      0.998472  rom são vicent pallótt presbíter fund sociedad...
25    4496      0.998451  memór sant isabel hungr send jov dad cas luí l...
26    2601      0.998431  sant bríg religi contra matrimóni suéc sen ulf...
27    1652      0.998407  senh fát portug cuj contempl lug aljustrel mãe...
28    3818      0.998381  memór sant terês menin jesu virgem dou igrej e...
29    1024      0.998322  valdsten suéc sant catarin virgem filh sant br...

TOP MENOS SIMILARES

    indice  similaridade                                          documento
0     1632      0.769721   varenn territóri langr gál act franç são gengulf
1     1550      0.771943        vienn gál lionens act franç são nicéci bisp
2     2029      0.772539      auxerr gál lionens act franç são censúri bisp
3     1084      0.774590         senlil gál lugdun act franç são régul bisp
4     2589      0.775321           menat gál arven act franç são menel abad
5      188      0.776012             gévaudan gál act franç são firmin bisp
6     4068      0.777156  orang provenç reg gál act franç são florênci bisp
7     3091      0.777207            metz gál bélg act franç são firmin bisp
8     4633      0.777719           carpentr provenç act franç são sifr bisp
9      566      0.778342  château-landon gál act franç são severin abad ...
10    3271      0.778409                  saint gál act franç são vivi bisp
11    3787      0.778481      auxerr gál lionens act franç são fratern bisp
12     585      0.778861  carcasson gál narbon act franç são guim gumar ...
13    4381      0.779017             verdun gál bélg act franç são vit bisp
14    1849      0.780122  orang provenç reg gál act franç sant eutrópi bisp
15    2514      0.780194      auxerr gál lionens act franç são teodósi bisp
16    3933      0.783131          ruã gál lionens act franç sant evódi bisp
17    2764      0.783650         auxerr gál lionens act franç sant urs bisp
18    1586      0.783866       auxerr gál lionens act franç sant eládi bisp
19    4138      0.784174            auch aquitân act franç são leotádi bisp
20     587      0.784478           meaux reg bri act franç são gilbert bisp
21    2910      0.784915     bordéu aquitân act franç são múmul abad fleury
22    3230      0.785421    auxerr gál lionens act franç sant eleutéri bisp
23    3388      0.786183            chartr nêustr act franç são calétr bisp
24     204      0.786348            chartr nêustr act franç são malard bisp
25    1417      0.786445          vienn borgonh act franç são clarênci bisp
26     529      0.786697         besançon borgonh act franç são nicéci bisp
27      48      0.786741            meaux nêustr act franç são rigomer bisp
28     551      0.786946              saint aquitân act franç são troi bisp
29    3287      0.787003            metz gál bélg act franç sant adelf bisp